[build]
incremental = true
rustflags = ["--cfg", "tokio_unstable"]

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"

[target.aarch64-linux-android]
linker = "aarch64-linux-android26-clang"
ar = "aarch64-linux-android-ar"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi26-clang"
ar = "armv7a-linux-androideabi-ar"

[alias]
ck = "check --workspace"
cl = "clippy --workspace --all-targets -- -D warnings"
t  = "test --workspace"
fmt-check = "fmt --all -- --check"
